---
title: "02_clean_prepost_grades"
author: "Juan Ospina"
date: "2/12/2019"
output: html_document
---

```{r}
source("../R/custom_functions.R")
```

```{r}
ds_intv <-
  read_csv("../../LTB Data/LTB Intervention Data/Participants Fall '16 - Spring '17 (de-identified).csv")
```

```{r}
dsl_all %>% 
  head
```
```{r}
dsl_all %<>% 
  mutate(
    term_f = as.factor(term)
  )
```

```{r}
dsl_all %>% 
  count(term, term_f, term_c)
```

```{r}
ds_intv %<>% 
  mutate(
    cond = `Condition (1 = Con, 2 = Inter, 3 = Letter)`,
    cond = as.factor(cond),
    cond = factor(
      cond,
      levels = c(1, 
                 2,
                 3),
      labels = c("control", 
                 "intv",
                 "letter")
    )
  )

ds_intv %>% 
  count(
    `Condition (1 = Con, 2 = Inter, 3 = Letter)`, cond
  )
```

```{r}
ds_intv %<>% 
  mutate(
    date_session1 = mdy(`Session 1`),
    date_session2 = mdy(`Session 2`)
  )

# to check all dates one by one
# ds_intv %>% 
#   select(`Session 1`, date_session1, `Session 2`, date_session2)
```

```{r}
ds_intv1 <- ds_intv

ds_intv %<>% 
  select(
    Participant, cond, date_session1, date_session2
  )
```

```{r}
ds_intv
```

```{r}
dsl_all %>% 
  select(Participant) %>% 
  unique

dsl_all %>% 
  select(term) %>% 
  unique

# ds_intv %>% 
#   select(date_session1) %>% 
#   unique

ds_intv %>% 
  select(date_session1) %>% 
  unique
```

```{r}
dsl_intv <-
  dsl_all %>% 
  left_join(ds_intv, by = "Participant")
```

```{r}
ds_date <-
  read_rds("../../LTB Data/LTB School Data/dates_acad_year.rds")

ds_date %<>% slice(rep(1:n(), each = nrow(dsl_intv)))

dsl_intv %<>% 
  bind_cols(ds_date)
```

```{r pre post measure}
dsl_intv %<>% 
  mutate(
    date_diff_fall_intv = date_session1 - fall_start,
    date_diff_spring_intv = date_session1 - spring_start
  )

dsl_intv %>% 
  select()
```

```{r}
dsl_intv %>% 
  select(date_session1) %>% 
  unique %>% 
  arrange(date_session1)

dsl_intv %>% 
  select(term_c) %>% 
  unique %>% 
  arrange(term_c)

head(dsl_intv)

dsl_intv %>% 
  count(date_diff_fall_intv) %>% 
  unique %>% 
  arrange(date_diff_fall_intv)
```

```{r grades}
# get all the codes of their grades
dsl_intv %>% 
  count(grade_c) %>% 
  write_csv("../../LTB Data/LTB School Data/Grade codes.csv")

# Need to change letter grade to 4.0 
letter.code <- c(
  "4.3" = "A+",
  "4" = "A",
  "3.7" = "A-",
  "3.3" = "B+",
  "3.0" = "B",
  "2.7" = "B-",
  "2.3" = "C+",
  "2.0" = "C",
  "1.7" = "C-",
  "1.3" = "D+",
  "1.0" = "D",
  "0.7" = "D-",
  "0.3" = "F+",
  "0.0" = "F",
  "0.0" = "F-" # need to double-check these with Greg and Daniel
  # ? = "CR"
  # ? = "I"
  # "0.0" = "NC",
  # "0.0" = "NM",
  # "3.24" = "P",
  # "2.94" = "W"
  )

dsl_intv$grade_num <- letter2point(dsl_intv, "grade_c") 

# Make sure grade points match original letter grades
table(dsl_intv$grade_c, dsl_intv$grade_num)

dsl_intv %>% 
  count(grade_num, grade_c) %>% 
  kable

dsl_intv$grade_num <- as.numeric(dsl_intv$grade_num) # Need to change to numeric

hist(dsl_intv$grade_num)
```


```{r}
# Problem: the threshold is arbitrary, we need to draw conclusions on all the 
# extremes of the possible thresholds. If that is even the optimal solution.

# dsl_intv1 <- dsl_intv

dsl_intv %<>%
  group_by(Participant) %>% 
  mutate(
    # intv_post = ifelse(
    #   term_c >= "Fall 2016-2017",
    #   # & date_diff_fall_intv > 30 & !is.na(grade_num) 
    #   1, # for those who started the intervention after being one month in classes
    #   ifelse(
    #     term_c == "Fall 2016-2017" & date_diff_fall_intv > 30, 0, 0
    #     # ifelse(
    #     #  is.na(grade_num), NA, 0
    #     # )
    #   )
    # ),
    intv_post = ifelse(
      term_c >= "Fall 2016-2017", 1, 0
    ),
    intv_post = ifelse(
      term_c == "Fall 2016-2017" & date_diff_fall_intv > 30, 0, intv_post 
      # the 30 is arbitrary
    )
  ) %>% 
  ungroup()

dsl_intv %<>% 
  mutate(
    intv_post1 = intv_post,
    intv_post = ifelse(is.na(grade_num), NA, intv_post1)
  )

dsl_intv %>% 
  count(grade_num, intv_post, intv_post1)

# To check that all participants that have numeric grades actually
dsl_intv %>% 
  filter(
    !is.na(grade_num) & is.na(intv_post)
  ) %>% 
  select(Participant, starts_with("grade"), intv_post)

participant_check <-
dsl_intv %>% 
  select(
    Participant, grade_c, grade_num, name_c, term_c, date_session1, fall_start, 
    date_diff_fall_intv, intv_post, intv_post1
    ) %>% 
  filter(!is.na(grade_c)) %>% 
  arrange(Participant, term_c)
  # View

# participant_check %>% 
#   write_csv("participant_check.csv")

participants <-
  dsl_intv %>% 
  select(Participant) %>% 
  unique()

# Notes about reviewing the pre- post-intervention measure. If good, this means that the participant has pre- and post-intervention data
notes <-
  tribble(
    ~Participant, ~Note,
    "P02",        "No post-intv data",
    "P03",        "Good",
    "P04",        "Good",
    "P05",        "Good",
    "P08",        "Good",
    "P09",        "Good",
    "P10",        "Good",
    "P14",        "No post-intv data - the date of the intervention was 44 days (over 30 days) past",
    "P16",        "No post-intv data",
    "P17",        "No post-intv data - the date of the intervention was 37 days (over 30 days) past",
    "P18",        "Good",
    "P20",        "Good",
    "P21",        "Good",
    "P22",        "Has pre-intv data but only has one value in post-intv data",
    "P23",        "No post-intv data",
    "P27",        "No post-intv data",
    "P28",        "No post-intv data",
    "P29",        "Good",
    "P30",        "No post-intv data - the date of the intervention was 80 days (over 30 days) past",
    "P31",        "Good",
    "P32",        "No pre-intv data",
    "P33",        "No intervention at all",
    "P34",        "Good",
    "P36",        "No post-intv data - the date of the intervention was 102 days (over 30 days) past"
    "P38",        "Good, but no intervention until 183 after fall quarter start, 29 days after spring quarter start",
    "P39",        "Good",
    "P40",        "No post-intv data - the date of the intervention was 115 days (over 30 days) past",
    "P44",        "No intervention until 190 after fall quarter start, 36 days after spring quarter start, No post-intv data",
    "P46",        "Good, but no intervention until 186 after fall quarter start, 32 days after spring quarter start",
    "P50",        "No post-intv data, No intervention until 206 after fall quarter start, 52 days after spring quarter start",
    "P54",        "No post-intv data, No intervention until 253 after fall quarter start, 99 days after spring quarter start ",
    "P56",        "Good, but no intervention until 235 after fall quarter start, 81 days after spring quarter start",
    "P58",        "No post-intv data, No intervention until 241 after fall quarter start, 87 days after spring quarter start",
    "P59",        "Good, but no intervention until 242 after fall quarter start, 88 days after spring quarter start",
    "P60",        "Good, but no intervention until 256 after fall quarter start, 102 days after spring quarter start",
    "P62",        "No post-intv data, No intervention until 263 after fall quarter start, 109 days after spring quarter start",
    "P63",        "Good, but no intervention until 262 after fall quarter start, 108 days after spring quarter start",
    "S01",        "No intervention",
    "S02",        "No intervention",
    "S03",        "No intervention",
    "S07",        "No intervention"
  )
```

# Export cleaned grades dataset in long format

```{r}
dsl_intv %>% 
  write_csv("../../LTB Data/LTB School Data/Grade data for Lifting the Bar (FINAL) Long Format.csv")

dsl_intv %>% 
  write_rds("../../LTB Data/LTB School Data/Grade data for Lifting the Bar (FINAL) Long Format.rds")
```
