---
title: "10_clean_attendance"
author: "Juan Ospina"
date: "2/13/2019"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
---

```{r global options, echo=FALSE}
knitr::opts_chunk$set(
  # fig.path = 'figs/', fig.show = 'asis', 
  dpi = 75, 
  # include = FALSE, 
  echo = FALSE, # run the code, show me only the graphs
  warning = FALSE, message = FALSE, cache = FALSE)
```

```{r}
ds_a <- read.xlsx("../../LTB Data/LTB School Data/Attendance for Lifting the Bar (FINAL).xlsx", sheet = 1, detectDates = TRUE, startRow = 1, colNames = TRUE)
```

```{r}
ds_a %>% 
  count(`Pre-Intervention.(0).or.Post-Intervention.(1)`)
```

```{r}
ds_a %<>% 
  rename(
    Participant = `Participant.#`,
    fall_start = Fall.Semester.Start,
    fall_end = Fall.Semester.End,
    spring_start = Spring.Semester.Start,
    spring_end = Spring.Semester.End
  )

ds_a1 <- 
  ds_a %>% 
    select(
      Participant, fall_start, fall_end, spring_start, spring_end
    )
```

```{r}
ds_a1 %<>% 
  filter(!is.na(Participant))

ds_a2 <- ds_a1

ds_a2 %<>% 
  filter(!is.na(fall_start)) %>% 
  filter(Participant != "Dewey Academy") %>% 
  unique

date_acad_year <-
  ds_a2 %>% 
  select(
    fall_start, fall_end, spring_start, spring_end
  ) %>% 
  unique

date_acad_year %>% 
  write_rds("../../LTB Data/LTB School Data/dates_acad_year.rds")
```

# Understand codes of variables

```{r}
# ds_a %>% names %>% noquote()

ds_a %>% 
  count(`Y/-.(Present)`) %>% 
  kable_format()

ds_a %>% 
  count(`A.(Absent,.Unverified)`) %>% 
  kable_format()

ds_a %>% 
  count(`T.(Tardy)`) %>% 
  kable_format()

ds_a %>% 
  count(`X.(Excused.Absence)`) %>% 
  kable_format()

ds_a %>% 
  count(`S.(Suspended)`) %>% 
  kable_format()

ds_a %>% 
  count(`I.(Illness)`) %>% 
  kable_format()

ds_a %>% 
  count(`P.(Personal)`) %>% 
  kable_format()

ds_a %>% 
  count(`V.(School.activity)`) %>% 
  kable_format()

ds_a %>% 
  count(`M.(Tardy.30+.Minutes)`) %>% 
  kable_format()

ds_a %>% 
  count(`O.(Out.on.Home.study)`) %>% 
  kable_format()

ds_a %>% 
  count(`U.(Unexcused.Absence)`) %>% 
  kable_format()

ds_a %>% 
  count(`Z.(Administrative.suspension)`) %>% 
  kable_format()

ds_a %>% 
  count(`NE.(Not.Enrolled)`) %>% 
  kable_format()

ds_a %>% 
  count(`H.(In-school.suspension)`) %>% 
  kable_format()

ds_a %>% 
  count(`J.(Juvenile.detention)`) %>% 
  kable_format()
```

